name: Deploy

on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout OrnaCodexCrawler
        uses: actions/checkout@v4
        with:
          repository: '67au/OrnaCodexCrawler'
          path: './crawler'
      - name: Download Codex from Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: codex
          path: './crawler/output'
          branch: main
          workflow: crawl.yml
          github_token: ${{ secrets.GH_PAT }}
          repo: 67au/OrnaCodexCrawler
      - name: Setup Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.13
      - run: |
          uv sync --directory ./crawler
          uv run --directory ./crawler main.py realm_raids --extra ../public
      - name: Move realm.json
        run: |
          mv public/realm.json src/assets
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: |
          pnpm build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=${{ vars.CF_PAGES_NAME }}
